Add filtering to myeloid panel
eastgenomics/eggd_vcf_handler_for_uranus pull request #29
Opened 2021-12-16 16:51 UTC by jethror1

- Adds filtering of myeloid variants that are >50% previous count or synonymous, except for those in TP53 and GATA2, to a separate myeloid_filtered tab to reduce total variants for initial review
- Addition of formatted 'to report' tab to save scientists time creating for each analysis
- Better formatting of output xlsx file

2021-12-16 16:51 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/vcf_handler.py`](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/64e03f318d48ba02efae267f7f31b88eeae2289c/resources/home/dnanexus/vcf_handler.py):

> [Line 394:80](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/64e03f318d48ba02efae267f7f31b88eeae2289c/resources/home/dnanexus/vcf_handler.py#L394): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> [Line 517:5](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/64e03f318d48ba02efae267f7f31b88eeae2289c/resources/home/dnanexus/vcf_handler.py#L517): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented

2022-01-05 12:51 UTC, Aisha-D requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 406 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29#-MseHCKX5RILqKmDIjIl:-MseHCKX5RILqKmDIjIm:b-266hv6) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/4154ccd649977c708ffcf95d1899b827d17b3d66/resources/home/dnanexus/vcf_handler.py#L406)):*
> ```Python
>     for label in col1_labels:
>         report_df = report_df.append(
>             {report_df.columns[0]: label}, ignore_index=True
> ```

a comment to explain what this loop is doing
___
*[resources/home/dnanexus/vcf_handler.py, line 412 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29#-MseHHFH1XWBvA5QCWm7:-MseHHFH1XWBvA5QCWm8:bxk3wd9) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/4154ccd649977c708ffcf95d1899b827d17b3d66/resources/home/dnanexus/vcf_handler.py#L412)):*
> ```Python
> 
>     col6_label_idx = 8
>     for label in col6_labels:
> ```

another comment


<!-- Sent from Reviewable.io -->

2022-01-05 16:39 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @woook)

___
*[resources/home/dnanexus/vcf_handler.py, line 406 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29#-MseHCKX5RILqKmDIjIl:-Msf5jE29K7V7VaS74y3:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/4154ccd649977c708ffcf95d1899b827d17b3d66/resources/home/dnanexus/vcf_handler.py#L406)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

a comment to explain what this loop is doing
</blockquote></details>

Done.
___
*[resources/home/dnanexus/vcf_handler.py, line 412 at r2](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29#-MseHHFH1XWBvA5QCWm7:-Msf5jeZB468zGkqzj57:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/4154ccd649977c708ffcf95d1899b827d17b3d66/resources/home/dnanexus/vcf_handler.py#L412)):*
<details><summary><i>Previously, Aisha-D wrote…</i></summary><blockquote>

another comment
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-06 11:29 UTC, Aisha-D reviewed
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29)* status: all files reviewed, 2 unresolved discussions (waiting on @Aisha-D and @woook)



<!-- Sent from Reviewable.io -->

2022-01-06 11:30 UTC, Aisha-D approved these changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vcf_handler_for_uranus/29)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woook)



<!-- Sent from Reviewable.io -->

2022-01-06 11:31 UTC, merged